# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: DEV

replicaCount: 1

image:
  repository: docker.pkg.github.com/mlambda-net/identity/api
  tag: "latest"
  pullPolicy: Always


imagePullSecrets:
  - name: regdocker

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /check/user/metrics
  prometheus.io/port: "8002"

podSecurityContext: {}

securityContext: {}

variables:
  secret: abc

service:
  type: NodePort
  ports:
     http: 8001
     metrics: 8002
     swagger: 8003

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: issuer-prod

  hosts:
    - host: api.mlambda.me
    - host: api.mitienda.co.cr
  tls:
    - secretName: api-tls
      hosts:
        - api.mlambda.me
        - api.mitienda.co.cr

resources:
   limits:
     cpu: 50m
     memory: 50Mi
   requests:
     cpu: 50m
     memory: 50Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
