# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: DEV

replicaCount: 1

image:
  repository: mlambdanet/identity-api
  tag: "latest"
  pullPolicy: Always


imagePullSecrets:
  - name: image-pull-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /check/identity/metrics
  prometheus.io/port: "8001"

podSecurityContext: {}

securityContext: {}


app:
  name: identity
  secret: abc
  port: 8000
  host: api-dev.mitienda.co.cr
  metric:
    port: 8001
  docs:
    port: 8002
  oauth:
    port: 8004
    host: oauth-dev.mitienda.co.cr
    clientId: identity
    secret: 123
  remote:
    host: server
    port: 8090
  cache:
    server: cache
    port: 6379
    db: 0
    password: ""


service:
  type: NodePort
  ports:
     http: 8000
     metrics: 8001
     swagger: 8002
     oauth: 8004



ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api-dev.mitienda.co.cr
      paths:
        - path: /user
          backend:
            serviceName: api
            servicePort: 8000
        - path: /swagger
          backend:
            serviceName: api
            servicePort: 8002
    - host: oauth-dev.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: api
            servicePort: 8004


resources:
   limits:
     cpu: 100m
     memory: 200Mi
   requests:
     cpu: 80m
     memory: 50Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
# targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
