version: '3.7'
services:

  cache:
    ports:
      - "6379:6379"
    build:
      context: .
      dockerfile: docker/cache/Dockerfile

  data:
    ports:
      - "5432:5432"
    build:
      dockerfile: docker/db/Dockerfile
      context: .

  migrate:
    command: -configFiles=/db/flyway.conf -connectRetries=60 clean migrate
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    depends_on:
      - data

  server:
    ports:
      - "8090:8090"
    env_file:
      - env/local_server.env
    build:
      context: .
      dockerfile: docker/server/Dockerfile

  api:
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8004:8004"
    env_file:
      - env/local_api.env
    build:
      context: .
      dockerfile: docker/api/Dockerfile

  web:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        DOCKERPASS: ${DOCKERPASS}
        ENV: dev

