version: '3.7'
services:

  data:
    ports:
      - "5432:5432"
    build:
      dockerfile: docker/db/Dockerfile
      context: .

  migrate:
    command: -configFiles=/db/flyway.conf -connectRetries=60 migrate
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    depends_on:
      - data

  server:
    ports:
      - "8090:8090"
    env_file:
      - env/dev_server.env
    build:
      context: .
      dockerfile: docker/server/Dockerfile

  api:
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    env_file:
      - env/dev_api.env
    build:
      context: .
      dockerfile: docker/api/Dockerfile
