apiVersion: skaffold/v2beta8
kind: Config

metadata:
  name: user

build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"

  local:
    push: true
    useDockerCLI: true

  artifacts:
    - image: mlambdanet/identity-server
      context: .
      docker:
        dockerfile: docker/server/Dockerfile

    - image: mlambdanet/identity-api
      context: .
      docker:
        dockerfile: docker/api/Dockerfile

    - image: mlambdanet/identity-web
      context: .
      docker:
        dockerfile: docker/web/Dockerfile
        buildArgs:
          ENV: "{{.ENV}}"
          PACKTOKEN: "{{.PACKTOKEN}}"

    - image: mlambdanet/identity-cache
      context: .
      docker:
        dockerfile: docker/cache/Dockerfile

    - image: mlambdanet/identity-index
      context: .
      docker:
        dockerfile: docker/index/Dockerfile


profiles:
  - name: QA
    deploy:
      helm:
        releases:
          - name: cache
            namespace: identity
            chartPath: helm/cache
            valuesFiles: [helm/cache/values.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"

          - name: server
            namespace: identity
            chartPath: helm/server/chart
            valuesFiles: [helm/server/chart/values.yaml, helm/server/env/qa.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"
              app.secret: "{{.SECRET_KEY}}"
              app.db.user: "{{.DB_USER}}"
              app.db.password: "{{.DB_PASSWORD}}"
              app.db.host: "{{.DB_HOST}}"

          - name: api
            namespace: identity
            chartPath: helm/api/chart
            valuesFiles: [helm/api/chart/values.yaml, helm/api/env/qa.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"
              app.secret: "{{.SECRET_KEY}}"

          - name: web
            namespace: identity
            chartPath: helm/web/chart
            valuesFiles: [helm/web/chart/values.yaml, helm/web/env/qa.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"


  - name: PROD
    deploy:
      helm:
        releases:
          - name: cache
            namespace: identity
            chartPath: helm/cache
            valuesFiles: [helm/cache/values.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"

          - name: server
            namespace: identity
            chartPath: helm/server/chart
            valuesFiles: [helm/server/chart/values.yaml, helm/server/env/prod.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"
              app.secret: "{{.SECRET_KEY}}"
              app.db.user: "{{.DB_USER}}"
              app.db.password: "{{.DB_PASSWORD}}"
              app.db.host: "{{.DB_HOST}}"

          - name: api
            namespace: identity
            chartPath: helm/api/chart
            valuesFiles: [helm/api/chart/values.yaml, helm/api/env/prod.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"
              app.secret: "{{.SECRET_KEY}}"

          - name: web
            namespace: identity
            chartPath: helm/web/chart
            valuesFiles: [helm/web/chart/values.yaml, helm/web/env/prod.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"
