apiVersion: skaffold/v2beta8
kind: Config

metadata:
  name: user

build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  local:
    push: true
    useDockerCLI: true
  artifacts:
    - image: docker.pkg.github.com/mlambda-net/identity/user
      context: .
      docker:
        dockerfile: docker/server/Dockerfile

    - image: docker.pkg.github.com/mlambda-net/identity/api
      context: .
      docker:
        dockerfile: docker/api/Dockerfile

profiles:
  - name: QA
    deploy:
      helm:
        releases:
          - name: server
            namespace: identity
            chartPath: helm/server/chart
            valuesFiles: [helm/server/chart/values.yaml, helm/server/env/qa.yaml]
            setValueTemplates:
              image.tag: "{{.VERSION}}"

          - name: api
            namespace: identity
            chartPath: helm/api/chart
            valuesFiles: [helm/api/chart/values.yaml, helm/api/env/qa.yaml]
            setValueTemplates:
             image.tag: "{{.VERSION}}"


