# Default values for user server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


env: DEV

replicaCount: 1

image:
  repository: mlambdanet/identity-server
  name: user
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: image-pull-secret


app:
  name: server
  port: 8090
  secret: abc
  db:
    user: postgres
    password: postgres
    data: postgres
    host: data
    port: 5432
  metric:
    port: 8091
  cache:
    server: cache
    port: 6379
    db: 0
    password: ""
  index:
    server: http://index
    authenticate: false
    user: ""
    password: ""
  email:
    server: exchange
    port: 80



nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8090

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"

  hosts:
    - host: server-dev.mitienda.co.cr


resources:
   limits:
     cpu: 100m
     memory: 200Mi
   requests:
     cpu: 80m
     memory: 50Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
# targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
