# Default values for user server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


env: DEV

replicaCount: 1

image:
  repository: docker.pkg.github.com/mlambda-net/identity/
  name: user
  tag: "latest"
  pullPolicy: Always


app:
  name: server
  port: 8090
  secret: abc
  db:
    user: postgres
    password: postgres
    data: postgres
    host: data
    port: 5432
  metric:
    port: 8091
  cache:
    server: cache
    port: 6379
    db: 0
    password: ""
  index:
    server: http://index
    authenticate: false
    user: ""
    password: ""
  email:
    server: exchange
    port: 80


imagePullSecrets:
  - name: regdocker

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8090

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: issuer-prod

  hosts:
    - host: server-dev.mitienda.co.cr
  tls:
    - secretName: server-tls
      hosts:
        - server-dev.mitienda.co.cr

resources:
   limits:
     cpu: 50m
     memory: 50Mi
   requests:
     cpu: 50m
     memory: 50Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
