apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  ENV: "{{.Values.env}}"
  SECRET_KEY: "{{.Values.app.secret}}"
  APP_NAME: "{{.Values.app.name}}"
  APP_PORT: "{{.Values.app.port}}"
  APP_HOST: "{{.Values.app.host}}"
  APP_OAUTH_PORT: "{{.Values.app.oauth.port}}"
  METRIC_PORT: "{{.Values.app.metric.port}}"
  DOCS_HOST: "{{.Values.app.host}}"
  DOCS_PORT: "{{.Values.app.docs.port}}"
  REMOTE_SERVER: "{{.Values.app.remote.host}}"
  REMOTE_PORT: "{{.Values.app.remote.port}}"
  OAUTH_HOST: "{{.Values.app.oauth.host}}"
  OAUTH_CLIENTID: "{{.Values.app.oauth.clientId}}"
  OAUTH_SECRET: "{{.Values.app.oauth.secret}}"
  CACHE_SERVER: "{{.Values.app.cache.server}}"
  CACHE_PORT: "{{.Values.app.cache.port}}"
  CACHE_DB: "{{.Values.app.cache.db}}"
  CACHE_PASSWORD: "{{.Values.app.cache.password}}"
