
replicaCount: 1

image:
  repository: mlambdanet/identity-web
  tag: "latest"
  pullPolicy: Always


imagePullSecrets:
  - name: image-pull-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80

ssl:
  enabled: false
  generateTLS: true
  defaultCN: identity.mitienda.co.cr
  defaultIPList:
    - 100.0.0.200

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: web-tls
      hosts:
        - identity.mitienda.co.cr
  hosts:
    - host: identity.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80

resources:
   limits:
     cpu: 50m
     memory: 64Mi
   requests:
     cpu: 50m
     memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
