# Default values for userserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


env: DEV

replicaCount: 1

image:
  repository: docker.pkg.github.com/mlambda-net/identity/
  name: user
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regdocker

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 9001

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: server.mlambda.me
    - host: server.mitienda.co.cr
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
     cpu: 50m
     memory: 50Mi
   requests:
     cpu: 50m
     memory: 50Mi

variables:
  user: postgres
  password: postgres
  data: postgres
  host: data
  port: 5432
  secret: abc

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
