app:
  name: identity
  secret: abc
  port: 8000
  host: api.mitienda.co.cr
  metric:
    port: 8001
  docs:
    port: 8002
  oauth:
    host: https://oauth.mitienda.co.cr
    port: 8004
    clientId: identity
    secret: 123
  remote:
    host: server
    port: 8090
  cache:
    server: cache
    port: 6379
    db: 0
    password: ""

ssl:
  enabled: true
  generateTLS: false
  defaultCN: mitienda.co.cr
  defaultIPList:
    - 100.0.0.200
  defaultSANList:
    - api.mitienda.co.cr
    - docs.mitienda.co.cr
    - oauth.mitienda.co.cr
  defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lSQUppVG1sYWhGdFJ6bDRqVHBYMDhDYWd3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1pHVm1ZWFZzZEMxallUQWVGdzB5TVRBMU1EY3dORFEzTURsYUZ3MHlNakExTURjdwpORFEzTURsYU1Ca3hGekFWQmdOVkJBTVREbTFwZEdsbGJtUmhMbU52TG1OeU1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNjYjRjS1l2NmVnTUkvMDhYK2d4V3FXL2RmRzgvOFRaUXc4Rk00OWQKS1ZYbEI5dFRGME5USFlIdUs1eHJ0alpscGFGZ2F4dWFsWjJxdWtmRmIrOHR0bnJrT0lXTjNjQTNMTFhMNXRRawpjaHNESEYzRWJ1NEhhYjhCQklET28vZGZoMDZmNUtxbDM5Ukh5M3hjb25uYVZTVE9ta1o3Ty9NRndRN1NpSW9ECnFwSjlmN1BVMFN6aXlPREhUOW1QamNGU2NVeGpuaHJMUWV1WGRlL2xXWmI0RW4vblQ1YllxU2RLZlF6bDJqZnQKYytGZTV3QjdPbWtzc0VuYndjeDBjaEZkNW85TXEyaTNMemxaNGdPMy80UldlcHcwMUtkeEFUNTgyeGcxL2RRbgpURnZIR1ZjUzl4NXovYnRVUmplUmFFbllsOXZoZGpxSnRqbUdIckNWNUhiUk1RSURBUUFCbzRHeE1JR3VNQTRHCkExVWREd0VCL3dRRUF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWUQKVlIwVEFRSC9CQUl3QURBZkJnTlZIU01FR0RBV2dCUitWbnZaRW5DQUVVcU9YOGlPSnMyM2hVZlltVEJPQmdOVgpIUkVFUnpCRmdoSmhjR2t1YldsMGFXVnVaR0V1WTI4dVkzS0NFMlJ2WTNNdWJXbDBhV1Z1WkdFdVkyOHVZM0tDCkZHOWhkWFJvTG0xcGRHbGxibVJoTG1OdkxtTnlod1JrQUFESU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWEKZTFDTFU2NDVpaWcxVVpuVlBWQXBRL1lPS0RHYUtMMzY3MzFHZ3VOMXQvcnhXVFNVa2pYSnFncXdHTFNaNHozegpxdTVxbHB2TFYzdDZQeUMxWVo2QmxmbEsvT2ZsRjFIZ3gzL2pjLzFEcDBkcDJSMU83Q2RXR2h5dmJMMk5hRkh6CmJhQkh5clVDVnVXcllFeUxSbTVnV051N0Z2YkErck5mYTRzd2RCQnYxYjQrK29DV2tWRVlQQm9LZmV4ZWFSS1YKQlF1clYvUUFDT0FhYnpuRmJ1ZEVVTW5DTndXU3lxb2lUNk9RT3hGVS9BdVFJcHc2MGpRaXZBVnFVeVhJUXRJYwo0RmZ4bTBvRmZ4RldVVUR1eWJvTnVEUnlydGM2MEtsdi9QTjZiWmc3dTVpV044eEdyTHNrd0xEb0VZQkV6WE85ClhoNXc2UnZiN3pvOTlBdmFwZ3lHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  defaultKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBc2NiNGNLWXY2ZWdNSS8wOFgrZ3hXcVcvZGZHOC84VFpRdzhGTTQ5ZEtWWGxCOXRUCkYwTlRIWUh1SzV4cnRqWmxwYUZnYXh1YWxaMnF1a2ZGYis4dHRucmtPSVdOM2NBM0xMWEw1dFFrY2hzREhGM0UKYnU0SGFiOEJCSURPby9kZmgwNmY1S3FsMzlSSHkzeGNvbm5hVlNUT21rWjdPL01Gd1E3U2lJb0RxcEo5ZjdQVQowU3ppeU9ESFQ5bVBqY0ZTY1V4am5ockxRZXVYZGUvbFdaYjRFbi9uVDViWXFTZEtmUXpsMmpmdGMrRmU1d0I3Ck9ta3NzRW5id2N4MGNoRmQ1bzlNcTJpM0x6bFo0Z08zLzRSV2VwdzAxS2R4QVQ1ODJ4ZzEvZFFuVEZ2SEdWY1MKOXg1ei9idFVSamVSYUVuWWw5dmhkanFKdGptR0hyQ1Y1SGJSTVFJREFRQUJBb0lCQUFTV1NMVEhaUGNaR0s4WgpDcVRDM2ZzanliUG1YK1VObERtSnVxMmc1bHQ1cnVZci81SGJGOXJzRGxRcnZnKytpWkxqZmhSbGF2Q3ZWOGRrCnNMQjVzR2xEOUgyTTNLTTdJWEZTNDRiNk5GS0paZVFtZXpvTmhEMXpRemgxaGw5dXM1VlBMd3I4YURsRlJmRDMKTFlDM3VpMTJQS3A0WlJlZjVxY2JsYzBXR3BBZEduWWtMbXBGb3UwSHVaLzg5SFdWNnd4UUtGaG5yWG15bmRnUgpYWVdCY00rNHBqM3pZekRDdVRaQjgzTFQwQVBJUStlZTZnK1ZEVm05a0tuWlVzVGZkSzlVQ3pWaFB6aitaaGY5CllhdW5Yd3lTL2ZUbHdHQTBZVEE4MDFwc0lsRUFmVnBiRXpVVkxkWFNtZi8vVGR2VVRJZGM2cHBPZlVBeWFTcFMKakx1ekJWRUNnWUVBNnkzd215b1hjdUtnNkgzbkNHbWRYRU43ZjZuVzNMQXBQdS8vNFUxcnFZbWJteFI1V1JXRApVQkczbXhZbkM2elM0QlN2UU9GMnUvajR0OHNzZ1BkZmR0WWNNcXdyZkQxTThlYWpaNE9BN1RSWUZKVVdsbVprCmNHK1VmQ0dQUm1mQzBzaXJ1V2dqcUYwVEI1Y0lsaWJTczNwUEkyNzhBWWU1YWowTUJyZDN0YjBDZ1lFQXdZUVQKKzZwb0VPQ01yVnZ0VUJyWk93YTU3bENjRHcremxEZndydnh1TEV2UDNhQWw5RzFhR3FzTEo5UVMzN2d0aytISgpWQUl2QWFDZkM0Ym10VHA0dm9aRm1uWjNIdzJJb0lyNUhqZTY4TWJLTFVqWVJMeFlqUUgrYWVPZEJ0OEdnYnlMCm44ZUtlZ2M3eDZ4cGwxRjlKWGdxTVZwK293WnU4bkRtam9oU1hvVUNnWUFRa1c3MjczTXhjOGZVT1RKeWhFWkMKdnJwUGx4NTg4NmdrTi9JMTVDZG1qVHc2STZvYzNZZ2Z0dS9SYkRFYUFIWG10VzVYU3NyN21TR2tpUnE4aHpEaApoVm45TStYb1hjVXk4WVduZ0Rzdit0VU50aWNlTjE1eUVWcExtRzJvanh6SmpydVNWMFRUMHFMSmtSbFl3cWxyClhYMS95SXpXYXNKa09xTERRbCtiblFLQmdFRk04MzFTRkluVmJFTTNxUTRGOFZYa3dDczJFbU5XdGcrSERQWFAKZ3RINXh5d1BWWjkwb3hvcXE3b0Y2MVNKRHdBL0NiUUtoSmcwL2xaaWNFbXBjSU5DUmd5SWUwd0VRaDJDcCt2VgpmSVN4WUJvRjRjellEYjJQZGExL3ZFWk1UaUxMWUFaTHpHTy9PeUgzQVM2cHRlUkY5MTd1SFp1Zm1TTEFqRngrCmplVU5Bb0dBY3BZQklpMU9sNG9PUk5US0syQWlxaWROcFdENEpUZEpOcFhZcXkvMGhtZXRKT3VWYWorRVExemYKWG1hTmlEclU1c09QNjNNb3VoK04ySFk2bXRnUWNWZjdMZUV6VVVKZEFQT0FlMTBxZGUwc3NwSHNFa0lvS09mMAphRXplam9ENHBMQm5TUkdYUm0wTzgrMjYyLzBFb2RQZlRWQXhXbjNGZVZCQVVaYmRhMnc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: api-tls
      hosts:
        - api.mitienda.co.cr
        - docs.mitienda.co.cr
        - oauth.mitienda.co.cr
  hosts:
    - host: api.mitienda.co.cr
      paths:
        - path: /identity
          backend:
            serviceName: api
            servicePort: 8000
    - host: docs.mitienda.co.cr
      paths:
        - path: /identity/swagger
          backend:
            serviceName: api
            servicePort: 8002
    - host: oauth.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: api
            servicePort: 8004

