app:
  name: server
  port: 8090
  secret: 6368616e676520746869732070617373776f726420746f206120736563726574
  db:
    user: postgres
    password: postgres
    data: identity
    host: data
    port: 5432
  metric:
    port: 8091
  cache:
    server: cache
    port: 6379
    db: 0
    password: ""
  index:
    server: http://index
    authenticate: false
    user: ""
    password: ""
  email:
    server: exchange
    port: 80

ssl:
  enabled: true
  generateTLS: false
  defaultCN: server.mitienda.co.cr
  defaultIPList:
    - 100.0.0.200
  defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lSQUwvc2ZiWVZveXV5aWNlUTIyQnU1Y2t3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1pHVm1ZWFZzZEMxallUQWVGdzB5TVRBMU1EY3dORFEzTURoYUZ3MHlNakExTURjdwpORFEzTURoYU1DQXhIakFjQmdOVkJBTVRGWE5sY25abGNpNXRhWFJwWlc1a1lTNWpieTVqY2pDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUpwaFB1Qy9QVjFDbzV1cHlXTzhEOWxXY3ZZbmZiVWYKSGthTHFMVjV0eVVrbmpDK1FNcjBIS2VsSzROSUYySnB2Qys0VnNTM3A4QStQN1RXYVFVb1h4OVF3YW1ZamdrQQpRdVV4KzRPSHdNYnhDeVBwK3R3eUYzK3Y4S3djRVJuVGZUMXRMcXRDTXlxaEZBbDFXVENCVEdLcHFqQVhSN2dHCjJ6TGxRblppSHNvcFB3QkxyR3pRRDNqMXpsT0RGS2lUcHNmRnc1b0VCV1MxRnRnOUNNTW03dlkvdkdtYTd4bmoKRzl4MzdqOVhCd3ZzNnRPb1l1OThHRmNqVXdtanNmMTQ2eHRuRXJ1Nm12VVMzZFZvb041SzgxSm9iT2M0bTcyMQpmVzh4eCtQQ05saUJ4RERMVnNXTnh4dTBuQjQ0YXAwWkNiUzFlcExROXM0eEE2Vk8zQU90K2owQ0F3RUFBYU54Ck1HOHdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0QKQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkNKVUZLVEgxdWpaV0VvbnlLRjFycGk5cFE1QgpNQThHQTFVZEVRUUlNQWFIQkdRQUFNZ3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ0g2c2RIQ2QrUnQyZ21zCi8xaVUrSGpySUwyZGR5enBPOEtCVG9aT0FBRkhLNVFQOTNkenB2SkFidXlNY3ROcC9UUmtnV3p5TTBITGtnTC8KbmdqdUZKazBHTURQVU1RdTZZYzZTbDVERmVieEpMYUg2T3JYR2Rud2FBYS9vUEt2NkFFYkpCRUNzSTQyU28zUQpZK0I2dXBKVStsTStqUDR2WVRETGhQQzRlbXdpMG1qS2hnb0RQRThWZmgxYTBSMnlHM240bk1iT2JzRUVYa1BUCjYwVHREUXF4dFFuRG5KallIZkk0MjlHaFpZanQyakw4dXl3Zi9qZXZncGNOSzV5WDFkTy81MURwV3JZZmlLK1UKd1FsdC9Db2k3U1I3RjB6UzBFeVUvanUxbk9KL2REL3NVbW1mQXRIZ1V3TmlpTlRhTk04RU5pWDR6UklmOFZtcgpGNWJCQXNvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  defaultKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb0FJQkFBS0NBUUVBbW1FKzRMODlYVUtqbTZuSlk3d1AyVlp5OWlkOXRSOGVSb3VvdFhtM0pTU2VNTDVBCnl2UWNwNlVyZzBnWFltbThMN2hXeExlbndENC90TlpwQlNoZkgxREJxWmlPQ1FCQzVUSDdnNGZBeHZFTEkrbjYKM0RJWGY2L3dyQndSR2ROOVBXMHVxMEl6S3FFVUNYVlpNSUZNWXFtcU1CZEh1QWJiTXVWQ2RtSWV5aWsvQUV1cwpiTkFQZVBYT1U0TVVxSk9teDhYRG1nUUZaTFVXMkQwSXd5YnU5ais4YVpydkdlTWIzSGZ1UDFjSEMrenEwNmhpCjczd1lWeU5UQ2FPeC9YanJHMmNTdTdxYTlSTGQxV2lnM2tyelVtaHM1emlidmJWOWJ6SEg0OEkyV0lIRU1NdFcKeFkzSEc3U2NIamhxblJrSnRMVjZrdEQyempFRHBVN2NBNjM2UFFJREFRQUJBb0lCQUdQNWYrZTUwUHA1TWt5WApXb1VNLzlLR2luSmdScWNwbk1pZ25zUFBLOHlROXlTbndIdnVORFJZNFdIbUtNYWhwSzNlbWNwUkNRQ1ZEMXFECjA0VDBqUTFSbGVqSGs0dStzSk9PbDh1bytTMmNZZE9ETGVLMVNjUjE0czBDYkF5bWloOWllbXVMdG1qdjRYTHkKbkt5dHZ4TFJ2eFhmcmFFK1IydWhUall0K3JSOW1mWXNvdTFrNGdZYjVVTElxTlpPS1Fyb2o1Zmd4NkNOSnRyawpkNnZHelBxU1N1Zk9mZFQ1TjBLZ0h6THQxcFZPS0NVdmxFb2VWdjNCdlhRdXlPQXNjOTJMcGxtbGgvOC81c1dwCjhrZlYyU3lIUGZmWFcyNVk0UEpnWkpOdUk0MGxOQnRYRGkvODlzZUtFaXFSR0ZJRHRzOWF4c0NaS2MrbC9mMTIKcVhZWDlnRUNnWUVBeXV0QnFrNjVZbzRrRnBzZXRjN2lVL0JqRklDN1l4YkNLNDNoWUxvS3o0TVA2aExyUG54dAp6UDVrQ3FWbXVvUi84MjRVRVF6aTBNYmZWOVJtKzF1ZTNHam82ZXczMGREUTRXK1N0NmJQdFNuL3VOVjJZS2NaCjdBRXc4OUJOVkVYb0Fsd1NsMTg4OFdqaGNWS2V1Zi9sbHVZZWgrWkxOMzE3WS9FSlFLdDBiYjBDZ1lFQXdzT0EKazZlMUpLSHJDWkFsejFWZ2VkVEdxL3ZRelJsTnhPakEvU3luSy9oTm9PQmNzVzYvTkJsUEJWZnVhNENBcWZOOAowcDZ1aDM2K2x5dFg2VEVnSjJkbmtoREZVRS9Xd0Nqb3RuaTlZM3NpVUdweG5tcmRqN1dGZnBBU1JnNUc5Nzh4ClhVdnB4L1g2bkk4bkw5eklkaTgzbWR1Z1IzbDhmM1J6VDUyVlJvRUNnWUFmeFVmSnQzdTFINVlzNStxZUFwOVQKRHg4a05hZWhNdzRCcmJ3czNkUVZlMnJCZG1iWXFMaTBVTnd2QW9pY0NXVFRJMWdHOTJLSDE2dGVZQVlqc3N1agpyTlZTMHNaR2xwQXR5NzlIKzlrbmYwVG5scHhyTTU2T1lmMWRIeThNVThtb25PdllRWFFVUkJ5UUZxUjljTUJzCnFPajgxQ1RRc2xmZ1pQdlM0VVZnYlFLQmdCZTdud1ZmSUZHd2NXV2U3UnlRdU1yZnhMM2NWNXRHaEJXRWowL0sKaXl4dWUzY3BIK0ozTGxGNDdBb29wdUx1cTc4SjdxSHp1Q3pHb3c3a3R6ZXhSc3ZHYS9aK21LeXFyZTZJamFMKwpuNFZwMGNxZXplMlI5Q0c0NnVWN1JON0lpcGxSOFAvL2FpTjFzKzR6KzRCM2xPM2gzeEtla3E5aS9HckRrL0dWCnNFVUJBbjhLbmc1Z1ppMWdvdEJOTGdFaG54WDJxeFlQQS9LNm1OdlF4NVhRQ0theVVUS041VEp4NXpVMGV1TmUKN3hpaFQ4NGlJbVZDZ2F0SG5xY0F5cnFiZHY2V2NKNGFIWjJFa2pqRnB5WUZwMmpWTVNDdERjSFdLck5saFIvcQpaNFZvUmw2REpmMW1Da0hWUHNwMVpjeVJ1VDJNWmkzMWtHM3FxajhNWnBwa2JEb0wKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  tls:
    - secretName: server-tls
      hosts:
        - server.mitienda.co.cr
  hosts:
    - host: server.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: server
            servicePort: 8090
