app:
  name: server
  port: 8090
  secret: 6368616e676520746869732070617373776f726420746f206120736563726574
  db:
    user: postgres
    password: postgres
    data: identity
    host: data
    port: 5432
  metric:
    port: 8091
  cache:
    server: cache
    port: 6379
    db: 0
    password: ""
  index:
    server: http://index
    authenticate: false
    user: ""
    password: ""
  email:
    server: exchange
    port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: issuer-prod
  tls:
    - secretName: server-tls
      hosts:
        - server.mitienda.co.cr
  hosts:
    - host: server.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: server
            servicePort: 8090
