ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: issuer-prod
  tls:
    - secretName: web-tls
      hosts:
        - identity.mitienda.co.cr
  hosts:
    - host: identity.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80

