ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: identity.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80
