ssl:
  enabled: true
  generateTLS: true
  defaultCN: identity.mitienda.co.cr
  defaultIPList:
    - 100.0.0.200

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: web-tls
      hosts:
        - identity.mitienda.co.cr
  hosts:
    - host: identity.mitienda.co.cr
      paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80

